version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'


  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    background = 'transparent'
    foreground = 'yellow'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
      type = 'git'
      style = 'plain'
      template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
      background = 'transparent'
      foreground = 'blue'
  
      [blocks.segments.properties]
        branch_icon = ''
        branch_identical_icon = '●'
        branch_max_length = 25.0
        fetch_stash_count = true
        fetch_status = true

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  background = 'transparent'
  template = '❯'


[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = 'transparent'
    foreground = 'blue'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    background = 'transparent'
    foreground = '#111111'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = true

[transient_prompt]
  foreground = 'yellow'
  background = 'transparent'
  template = '❯ '
